version: '3.4'
services:
  pg:
    image: postgres:11.9
    build: ./
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_HOST: ${DB_HOST}
  redis:
    image: redis
    ports:
      - 6379:6379

